TEST_VAL: name:"dev_cookie"
MONGODB_CONFIG:
  name: "test" # 自定义次数据库链接名称
  type: mongodb # 数据库链接类型
  url: "mongodb://localhost:27017" # 数据库链接地址
  username: "admin" # 数据库链接用户名
  password: "root" # 数据库链接密码
  database: "test" # 数据库名
  entities: "mongo" # 自定义加载类型
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能
